# Codemagic configuration file for Flutter project
workflows:
  flutter-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: 3.10.8
      groups:
        - tea-app-variables  # Имя группы переменных, которое вы создадите в интерфейсе
      android-sdk: default
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      # Создаем .env файл из переменных окружения
      - name: Create .env file
        script: |
          set -e
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_KEY=$SUPABASE_KEY" >> .env
          echo "API_URL=$API_URL" >> .env
          echo "APP_NAME=$APP_NAME" >> .env
          echo "Created .env file with environment variables"
      # Получаем зависимости Flutter
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      # Проверяем код
      - name: Analyze code
        script: |
          flutter analyze --no-fatal-infos --no-fatal-warnings
      # Собираем APK
      - name: Build APK
        script: |
          flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*-release.apk
    publishing:
      email:
        recipients:
          - ahalay994@gmail.com # Замените на ваш email
        notify:
          success: true
          failure: true

  flutter-ios:
    name: Build iOS IPA
    max_build_duration: 60
    environment:
      flutter: 3.10.8
      xcode: latest
      cocoapods: default
      groups:
        - tea-app-variables  # Имя группы переменных
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      # Создаем .env файл из переменных окружения
      - name: Create .env file
        script: |
          set -e
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_KEY=$SUPABASE_KEY" >> .env
          echo "API_URL=$API_URL" >> .env
          echo "APP_NAME=$APP_NAME" >> .env
          echo "Created .env file with environment variables"
      # Получаем зависимости Flutter
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      # Проверяем код
      - name: Analyze code
        script: |
          flutter analyze --no-fatal-infos --no-fatal-warnings
      # Собираем iOS архив и создаем IPA
      - name: Build iOS IPA
        script: |
          # Запускаем сборку IPA с отключенной подписью
          flutter build ios --release --no-codesign
          # Выводим список файлов в директории build для проверки
          echo "=== Содержимое build/ ==="
          find build/ -name "*" -type f | head -20
          echo "=== Содержимое build/ios/ ==="
          find build/ios/ -name "*" -type f | head -20
    artifacts:
      - build/**/Runner.app/**
      - build/**/Runner.ipa
      - build/**/Runner.ipa/**
      - build/**/Payload/**
      - build/**/build/**
    publishing:
      email:
        recipients:
          - ahalay994@gmail.com # Замените на ваш email
        notify:
          success: true
          failure: true

  flutter-multiplatform:
    name: Build Android APK & iOS IPA
    max_build_duration: 120
    environment:
      flutter: 3.10.8
      xcode: latest
      cocoapods: default
      groups:
        - tea-app-variables  # Имя группы переменных
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      # Создаем .env файл из переменных окружения
      - name: Create .env file
        script: |
          set -e
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_KEY=$SUPABASE_KEY" >> .env
          echo "API_URL=$API_URL" >> .env
          echo "APP_NAME=$APP_NAME" >> .env
          echo "Created .env file with environment variables"
      # Получаем зависимости Flutter
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      # Проверяем код
      - name: Analyze code
        script: |
          flutter analyze --no-fatal-infos --no-fatal-warnings
      # Собираем APK
      - name: Build APK
        script: |
          flutter build apk --release --split-per-abi
      # Собираем iOS архив и создаем IPA
      - name: Build iOS IPA
        script: |
          # Запускаем сборку IPA с отключенной подписью
          flutter build ios --release --no-codesign
          # Выводим список файлов в директории build для проверки
          echo "=== Содержимое build/ ==="
          find build/ -name "*" -type f | head -20
          echo "=== Содержимое build/ios/ ==="
          find build/ios/ -name "*" -type f | head -20
    artifacts:
      - build/app/outputs/flutter-apk/*-release.apk
      - build/**/Runner.app/**
      - build/**/Runner.ipa
      - build/**/Runner.ipa/**
      - build/**/Payload/**
      - build/**/build/**
    publishing:
      email:
        recipients:
          - ahalay994@gmail.com # Замените на ваш email
        notify:
          success: true
          failure: true